
CREATE TABLE IF NOT EXISTS stacks (
    id  INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    body_ru TEXT,
    body_en TEXT,
    html_ru TEXT,
    html_en TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
