
CREATE TABLE IF NOT EXISTS videos (
    id  INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    url  VARCHAR NOT NULL,
    title_ru TEXT,
    title_en TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
