
CREATE TABLE IF NOT EXISTS categories (
    id  INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name_ru VARCHAR UNIQUE,
    name_en VARCHAR UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
