
CREATE OR REPLACE VIEW modules_view AS
SELECT
    m.id,
    m.heading_ru,
    m.heading_en,
    m.body_ru,
    m.body_en,
    m.html_ru,
    m.html_en,
    m.priority,
    m.type,
    m.project_id,

    i1.alt_ru         AS first_alt_ru,
    i1.alt_en         AS first_alt_en,
    i1.variant        AS first_variant,
    i1.dk_webp_3x     AS first_dk_webp_3x,
    i1.dk_webp_2x     AS first_dk_webp_2x,
    i1.dk_webp        AS first_dk_webp,
    i1.dk_avif_3x     AS first_dk_avif_3x,
    i1.dk_avif_2x     AS first_dk_avif_2x,
    i1.dk_avif        AS first_dk_avif,
    i1.dk_tiny        AS first_dk_tiny,
    i1.tb_webp_3x     AS first_tb_webp_3x,
    i1.tb_webp_2x     AS first_tb_webp_2x,
    i1.tb_webp        AS first_tb_webp,
    i1.tb_avif_3x     AS first_tb_avif_3x,
    i1.tb_avif_2x     AS first_tb_avif_2x,
    i1.tb_avif        AS first_tb_avif,
    i1.tb_tiny        AS first_tb_tiny,
    i1.mb_webp_3x     AS first_mb_webp_3x,
    i1.mb_webp_2x     AS first_mb_webp_2x,
    i1.mb_webp        AS first_mb_webp,
    i1.mb_avif_3x     AS first_mb_avif_3x,
    i1.mb_avif_2x     AS first_mb_avif_2x,
    i1.mb_avif        AS first_mb_avif,
    i1.mb_tiny        AS first_mb_tiny,

    i2.alt_ru         AS second_alt_ru,
    i2.alt_en         AS second_alt_en,
    i2.variant        AS second_variant,
    i2.dk_webp_3x     AS second_dk_webp_3x,
    i2.dk_webp_2x     AS second_dk_webp_2x,
    i2.dk_webp        AS second_dk_webp,
    i2.dk_avif_3x     AS second_dk_avif_3x,
    i2.dk_avif_2x     AS second_dk_avif_2x,
    i2.dk_avif        AS second_dk_avif,
    i2.dk_tiny        AS second_dk_tiny,
    i2.tb_webp_3x     AS second_tb_webp_3x,
    i2.tb_webp_2x     AS second_tb_webp_2x,
    i2.tb_webp        AS second_tb_webp,
    i2.tb_avif_3x     AS second_tb_avif_3x,
    i2.tb_avif_2x     AS second_tb_avif_2x,
    i2.tb_avif        AS second_tb_avif,
    i2.tb_tiny        AS second_tb_tiny,
    i2.mb_webp_3x     AS second_mb_webp_3x,
    i2.mb_webp_2x     AS second_mb_webp_2x,
    i2.mb_webp        AS second_mb_webp,
    i2.mb_avif_3x     AS second_mb_avif_3x,
    i2.mb_avif_2x     AS second_mb_avif_2x,
    i2.mb_avif        AS second_mb_avif,
    i2.mb_tiny        AS second_mb_tiny

FROM modules m
LEFT JOIN images i1 ON i1.imageable_id = m.id AND i1.imageable_type = 'modules' AND i1.variant = 'first_image'
LEFT JOIN images i2 ON i2.imageable_id = m.id AND i2.imageable_type = 'modules' AND i2.variant = 'second_image'
ORDER BY p.priority DESC;
