[routes]
GET /api/home = Http\Controllers\HomeController->index

; GET /projects = Http\Controllers\ProjectController->index
GET /api/projects/@slug = Http\Controllers\ProjectController->edit
PUT /api/projects/@slug = Http\Controllers\ProjectController->update
